apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homelab-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - hello
  selector:
    matchLabels:
      app: hello
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
